"""Declarative base and shared column helpers for all ORM models.

A deterministic constraint-naming convention is set on the metadata so that the
initial Alembic migration (T-04-02) and every future autogenerated migration
produce stable, reviewable constraint names instead of database defaults.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Alembic-friendly naming convention (one source of truth for constraint names).
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base carrying the constraint naming convention."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key generated application-side (portable, deterministic)."""

    return mapped_column(primary_key=True, default=uuid.uuid4)


def created_at_column() -> Mapped[datetime]:
    """A non-null ``created_at`` timestamp defaulted by the database clock."""

    return mapped_column(server_default=func.now(), nullable=False)
