"""Generate AIMPOS-Spark backlog CSV files for Jira, ADO, and universal import."""
import csv
from pathlib import Path

OUT = Path(__file__).parent

ITEMS = [
    # EPICS
    {"type": "Epic", "id": "EPIC-01", "title": "Platform Foundation",
     "desc": "Runnable Olares stack: PostgreSQL, MinIO, Redis, Ollama, ComfyUI, API skeleton, health checks.",
     "parent": "", "epic": "EPIC-01", "feature": "", "priority": "P0", "points": "", "sprint": "S1",
     "labels": "aimpos-spark;foundation;olares",
     "ac": "Docker Compose starts all services with one command. /health returns OK. ComfyUI test image succeeds. Ollama responds locally with zero egress."},
    {"type": "Epic", "id": "EPIC-02", "title": "Pipeline Orchestration",
     "desc": "Temporal workflow skeleton with start, status, approve/reject signals, audit events.",
     "parent": "", "epic": "EPIC-02", "feature": "", "priority": "P0", "points": "", "sprint": "S2",
     "labels": "aimpos-spark;temporal;workflow",
     "ac": "User starts pipeline and sees status transitions. Workflow pauses at review gates. Approve advances; reject keeps stage. All transitions in audit_events."},
    {"type": "Epic", "id": "EPIC-03", "title": "Idea, Story & Script Stages",
     "desc": "Idea capture through approved script using Story Architect and Screenwriter agents.",
     "parent": "", "epic": "EPIC-03", "feature": "", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "aimpos-spark;agents;story;script",
     "ac": "Creator completes Idea to approved Story to approved Script in one run. Assets versioned in MinIO. Agent invocations logged with model ID."},
    {"type": "Epic", "id": "EPIC-04", "title": "Storyboard Stage",
     "desc": "ComfyUI storyboard frames from approved script, gallery review, approval.",
     "parent": "", "epic": "EPIC-04", "feature": "", "priority": "P0", "points": "", "sprint": "S4",
     "labels": "aimpos-spark;storyboard;comfyui",
     "ac": "4-6 frames generated locally. Gallery review with approve/reject/regenerate. GPU jobs sequenced without OOM."},
    {"type": "Epic", "id": "EPIC-05", "title": "Video & Pipeline Completion",
     "desc": "Short video generation, approval, export bundle, lineage summary.",
     "parent": "", "epic": "EPIC-05", "feature": "", "priority": "P0", "points": "", "sprint": "S5",
     "labels": "aimpos-spark;video;export",
     "ac": "15-30s video generated locally. Full pipeline end-to-end per demo script. Export ZIP with manifest."},
    {"type": "Epic", "id": "EPIC-06", "title": "Governance, Assets & Console",
     "desc": "Asset history, audit log, auth token, navigation shell, durability.",
     "parent": "", "epic": "EPIC-06", "feature": "", "priority": "P0", "points": "", "sprint": "S1-S5",
     "labels": "aimpos-spark;governance;ui",
     "ac": "All assets versioned and browsable. Full audit trail visible. Pipeline survives worker restart. API token auth on mutating endpoints."},

    # FEATURES
    {"type": "Feature", "id": "FEAT-01", "title": "Project Bootstrap",
     "desc": "Default project on startup. F-01.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-01", "priority": "P0", "points": "", "sprint": "S1",
     "labels": "feature;F-01", "ac": ""},
    {"type": "Feature", "id": "FEAT-INFRA", "title": "Infrastructure Enabler",
     "desc": "Docker Compose, health, schema, MinIO, Ollama/ComfyUI smoke tests.",
     "parent": "EPIC-01", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "", "sprint": "S1",
     "labels": "feature;infrastructure", "ac": ""},
    {"type": "Feature", "id": "FEAT-03", "title": "Start Production Pipeline",
     "desc": "Start Temporal workflow after idea capture. F-03.",
     "parent": "EPIC-02", "epic": "EPIC-02", "feature": "F-03", "priority": "P0", "points": "", "sprint": "S2",
     "labels": "feature;F-03", "ac": ""},
    {"type": "Feature", "id": "FEAT-16", "title": "Pipeline Status Dashboard",
     "desc": "Dashboard showing stage, progress, CTAs. F-16.",
     "parent": "EPIC-02", "epic": "EPIC-02", "feature": "F-16", "priority": "P0", "points": "", "sprint": "S2",
     "labels": "feature;F-16", "ac": ""},
    {"type": "Feature", "id": "FEAT-02", "title": "Capture Idea",
     "desc": "Title, paragraph, optional style note. F-02.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-02", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-02", "ac": ""},
    {"type": "Feature", "id": "FEAT-04", "title": "AI Story Generation",
     "desc": "Story Architect agent generates treatment. F-04.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-04", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-04", "ac": ""},
    {"type": "Feature", "id": "FEAT-05", "title": "Story Review & Approval",
     "desc": "Read, edit, approve/reject story. F-05.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-05", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-05", "ac": ""},
    {"type": "Feature", "id": "FEAT-06", "title": "AI Script Generation",
     "desc": "Screenwriter agent generates one-scene Fountain script. F-06.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-06", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-06", "ac": ""},
    {"type": "Feature", "id": "FEAT-07", "title": "Script Review & Approval",
     "desc": "Preview script, approve/reject. F-07.",
     "parent": "EPIC-03", "epic": "EPIC-03", "feature": "F-07", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-07", "ac": ""},
    {"type": "Feature", "id": "FEAT-08", "title": "AI Storyboard Generation",
     "desc": "Cinematography agent + ComfyUI frames. F-08.",
     "parent": "EPIC-04", "epic": "EPIC-04", "feature": "F-08", "priority": "P0", "points": "", "sprint": "S4",
     "labels": "feature;F-08", "ac": ""},
    {"type": "Feature", "id": "FEAT-09", "title": "Storyboard Gallery Review",
     "desc": "Grid gallery, approve/reject frames. F-09.",
     "parent": "EPIC-04", "epic": "EPIC-04", "feature": "F-09", "priority": "P0", "points": "", "sprint": "S4",
     "labels": "feature;F-09", "ac": ""},
    {"type": "Feature", "id": "FEAT-10", "title": "AI Short Video Generation",
     "desc": "ComfyUI image-to-video from frames. F-10.",
     "parent": "EPIC-05", "epic": "EPIC-05", "feature": "F-10", "priority": "P0", "points": "", "sprint": "S5",
     "labels": "feature;F-10", "ac": ""},
    {"type": "Feature", "id": "FEAT-11", "title": "Video Preview & Approval",
     "desc": "In-browser video preview and final approval. F-11.",
     "parent": "EPIC-05", "epic": "EPIC-05", "feature": "F-11", "priority": "P0", "points": "", "sprint": "S5",
     "labels": "feature;F-11", "ac": ""},
    {"type": "Feature", "id": "FEAT-14", "title": "Lineage Summary",
     "desc": "Idea to video chain visualization. F-14.",
     "parent": "EPIC-05", "epic": "EPIC-05", "feature": "F-14", "priority": "P1", "points": "", "sprint": "S5",
     "labels": "feature;F-14", "ac": ""},
    {"type": "Feature", "id": "FEAT-15", "title": "Export Final Bundle",
     "desc": "ZIP download with manifest.json. F-15.",
     "parent": "EPIC-05", "epic": "EPIC-05", "feature": "F-15", "priority": "P1", "points": "", "sprint": "S5",
     "labels": "feature;F-15", "ac": ""},
    {"type": "Feature", "id": "FEAT-12", "title": "Asset Version History",
     "desc": "Browse versions per stage. F-12.",
     "parent": "EPIC-06", "epic": "EPIC-06", "feature": "F-12", "priority": "P0", "points": "", "sprint": "S4",
     "labels": "feature;F-12", "ac": ""},
    {"type": "Feature", "id": "FEAT-13", "title": "Audit Log Viewer",
     "desc": "Chronological pipeline event log. F-13.",
     "parent": "EPIC-06", "epic": "EPIC-06", "feature": "F-13", "priority": "P0", "points": "", "sprint": "S3",
     "labels": "feature;F-13", "ac": ""},

    # USER STORIES
    {"type": "User Story", "id": "US-01", "title": "Create default project",
     "desc": "As a creator, I want a default project on startup so I can begin without setup.",
     "parent": "FEAT-01", "epic": "EPIC-03", "feature": "F-01", "priority": "P0", "points": "2", "sprint": "S1",
     "labels": "user-story;backend",
     "ac": "Given fresh deployment, one project AIMPOS Spark Demo exists. GET /projects returns project with status ACTIVE. Pipeline runs list is empty."},
    {"type": "User Story", "id": "US-02", "title": "Deploy MVP stack on Olares",
     "desc": "As a platform engineer, I want Docker Compose for all MVP services.",
     "parent": "FEAT-INFRA", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "5", "sprint": "S1",
     "labels": "user-story;devops",
     "ac": "docker compose up brings 9 containers healthy within 5 min. /health returns 200. MinIO upload/download round-trip works. All services on aimpos-spark network."},
    {"type": "User Story", "id": "US-03", "title": "API health and logging",
     "desc": "As a platform engineer, I want health checks and structured logs.",
     "parent": "FEAT-INFRA", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "2", "sprint": "S1",
     "labels": "user-story;backend",
     "ac": "GET /health includes postgresql, minio, redis, temporal status. Structured JSON logs with request_id. Failed dependency returns 503."},
    {"type": "User Story", "id": "US-04", "title": "Database schema foundation",
     "desc": "As a backend developer, I want core tables migrated.",
     "parent": "FEAT-INFRA", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "3", "sprint": "S1",
     "labels": "user-story;backend",
     "ac": "Tables: projects, pipeline_runs, asset_versions, approvals, audit_events, lineage_edges. Rollback works on empty DB. asset_versions has stage, version, minio_key, content_hash, is_ai_generated."},
    {"type": "User Story", "id": "US-05", "title": "MinIO asset upload service",
     "desc": "As a backend developer, I want reusable content-addressable asset storage.",
     "parent": "FEAT-INFRA", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "3", "sprint": "S1",
     "labels": "user-story;backend",
     "ac": "store_asset computes SHA-256 and stores at hash key. Metadata row content_hash matches ETag. Duplicate bytes deduplicated."},
    {"type": "User Story", "id": "US-06", "title": "Ollama and ComfyUI smoke test",
     "desc": "As an AI engineer, I want verified local model endpoints.",
     "parent": "FEAT-INFRA", "epic": "EPIC-01", "feature": "F-INFRA", "priority": "P0", "points": "3", "sprint": "S1",
     "labels": "user-story;ai",
     "ac": "Ollama generate responds in <30s. ComfyUI workflow writes PNG to MinIO. Sequential GPU use without OOM."},
    {"type": "User Story", "id": "US-07", "title": "Start pipeline workflow",
     "desc": "As a creator, I want to start production after entering my idea.",
     "parent": "FEAT-03", "epic": "EPIC-02", "feature": "F-03", "priority": "P0", "points": "5", "sprint": "S2",
     "labels": "user-story;workflow",
     "ac": "POST /pipeline/start creates SparkPipelineWorkflow. GET /pipeline/status shows STORY_GENERATING or STORY_REVIEW. Duplicate start returns 409. PipelineStarted audit event recorded."},
    {"type": "User Story", "id": "US-08", "title": "Approve or reject stage output",
     "desc": "As a creator, I want to approve or reject AI output at each stage.",
     "parent": "FEAT-03", "epic": "EPIC-02", "feature": "F-03", "priority": "P0", "points": "5", "sprint": "S2",
     "labels": "user-story;workflow",
     "ac": "POST /pipeline/approve with GRANT creates immutable approvals row. Approve advances workflow. Reject with note keeps stage. ApprovalGranted audit event logged."},
    {"type": "User Story", "id": "US-09", "title": "Regenerate after rejection",
     "desc": "As a creator, I want to regenerate AI output after rejecting it.",
     "parent": "FEAT-03", "epic": "EPIC-02", "feature": "F-03", "priority": "P0", "points": "3", "sprint": "S2",
     "labels": "user-story;workflow",
     "ac": "POST /pipeline/regenerate triggers agent for current stage. New asset_version with incremented version. Max 3 regenerations per stage (429 after). Rejection note passed to agent."},
    {"type": "User Story", "id": "US-10", "title": "View pipeline status dashboard",
     "desc": "As a creator, I want a dashboard showing stage and progress.",
     "parent": "FEAT-16", "epic": "EPIC-02", "feature": "F-16", "priority": "P0", "points": "3", "sprint": "S2",
     "labels": "user-story;frontend",
     "ac": "Dashboard shows stage, status, 5-step progress. REVIEW shows Go to Review CTA. GENERATING polls every 5s. FAILED shows error and Retry."},
    {"type": "User Story", "id": "US-11", "title": "Enter production idea",
     "desc": "As a creator, I want to enter title, paragraph, and style note.",
     "parent": "FEAT-02", "epic": "EPIC-03", "feature": "F-02", "priority": "P0", "points": "2", "sprint": "S3",
     "labels": "user-story;frontend",
     "ac": "Submit idea stores idea.txt v1 in MinIO. Style note in metadata. Appears under stage IDEA. Validation on required fields and 50-2000 char paragraph."},
    {"type": "User Story", "id": "US-12", "title": "Generate story from idea",
     "desc": "As a creator, I want Story Architect to generate a treatment.",
     "parent": "FEAT-04", "epic": "EPIC-03", "feature": "F-04", "priority": "P0", "points": "5", "sprint": "S3",
     "labels": "user-story;ai",
     "ac": "LangGraph Story Architect invoked. story.md on ai-draft branch. Audit logs model_id and agent. Local-only Ollama. Workflow to STORY_REVIEW."},
    {"type": "User Story", "id": "US-13", "title": "Review and edit story",
     "desc": "As a creator, I want to read, edit, and approve the story.",
     "parent": "FEAT-05", "epic": "EPIC-03", "feature": "F-05", "priority": "P0", "points": "3", "sprint": "S3",
     "labels": "user-story;frontend",
     "ac": "Review screen shows editable treatment. Save creates human-edit version. Approve advances pipeline. Reject enables regenerate."},
    {"type": "User Story", "id": "US-14", "title": "Generate one-scene script",
     "desc": "As a creator, I want Screenwriter to generate a Fountain script.",
     "parent": "FEAT-06", "epic": "EPIC-03", "feature": "F-06", "priority": "P0", "points": "5", "sprint": "S3",
     "labels": "user-story;ai",
     "ac": "Exactly 1 scene Fountain script. script.fountain is_ai_generated=true. Lineage edge story to script. Workflow to SCRIPT_REVIEW."},
    {"type": "User Story", "id": "US-15", "title": "Review and approve script",
     "desc": "As a creator, I want to preview and approve the script.",
     "parent": "FEAT-07", "epic": "EPIC-03", "feature": "F-07", "priority": "P0", "points": "3", "sprint": "S3",
     "labels": "user-story;frontend",
     "ac": "Fountain rendered with formatting. Approve advances to STORYBOARD_GENERATING. Reject/regenerate works. Approved version marked in DB."},
    {"type": "User Story", "id": "US-16", "title": "Generate storyboard frames",
     "desc": "As a creator, I want 4-6 storyboard images from my script.",
     "parent": "FEAT-08", "epic": "EPIC-04", "feature": "F-08", "priority": "P0", "points": "8", "sprint": "S4",
     "labels": "user-story;ai",
     "ac": "4-6 PNG frames via ComfyUI. Ollama unloaded before GPU. Lineage script to frames. STORYBOARD_REVIEW on success. Retry 2x then FAILED."},
    {"type": "User Story", "id": "US-17", "title": "Review storyboard gallery",
     "desc": "As a creator, I want to view frames in a grid and approve or reject.",
     "parent": "FEAT-09", "epic": "EPIC-04", "feature": "F-09", "priority": "P0", "points": "3", "sprint": "S4",
     "labels": "user-story;frontend",
     "ac": "Responsive grid of 4-6 images. Lightbox preview. Approve-all advances to video. Reject triggers regenerate. AI badge on frames."},
    {"type": "User Story", "id": "US-18", "title": "Generate short video clip",
     "desc": "As a creator, I want a short video from approved frames.",
     "parent": "FEAT-10", "epic": "EPIC-05", "feature": "F-10", "priority": "P0", "points": "8", "sprint": "S5",
     "labels": "user-story;ai",
     "ac": "scene_video.mp4 15-30s <=480p. Lineage frames to video. VIDEO_REVIEW on success. Slideshow fallback on failure."},
    {"type": "User Story", "id": "US-19", "title": "Preview and approve video",
     "desc": "As a creator, I want to preview video and complete the pipeline.",
     "parent": "FEAT-11", "epic": "EPIC-05", "feature": "F-11", "priority": "P0", "points": "3", "sprint": "S5",
     "labels": "user-story;frontend",
     "ac": "HTML5 player renders video. Approve sets COMPLETED. Reject enables regenerate. PipelineCompleted audit event."},
    {"type": "User Story", "id": "US-20", "title": "View asset lineage chain",
     "desc": "As a creator, I want to see idea to video lineage.",
     "parent": "FEAT-14", "epic": "EPIC-05", "feature": "F-14", "priority": "P1", "points": "3", "sprint": "S5",
     "labels": "user-story;frontend",
     "ac": "Ordered chain: idea to story to script to frames to video. Click node shows metadata. Data from lineage_edges PostgreSQL."},
    {"type": "User Story", "id": "US-21", "title": "Download production bundle",
     "desc": "As a creator, I want ZIP of approved assets with manifest.",
     "parent": "FEAT-15", "epic": "EPIC-05", "feature": "F-15", "priority": "P1", "points": "3", "sprint": "S5",
     "labels": "user-story;backend",
     "ac": "ZIP contains all approved assets and manifest.json with hashes, approvals, model IDs. BundleExported audit event."},
    {"type": "User Story", "id": "US-22", "title": "Browse asset versions",
     "desc": "As a creator, I want to see all versions per stage.",
     "parent": "FEAT-12", "epic": "EPIC-06", "feature": "F-12", "priority": "P0", "points": "3", "sprint": "S4",
     "labels": "user-story;frontend",
     "ac": "Versions grouped by stage. Newest first. Preview or download per version. Shows is_ai_generated, branch, content_hash."},
    {"type": "User Story", "id": "US-23", "title": "View audit trail",
     "desc": "As a creator, I want chronological pipeline event log.",
     "parent": "FEAT-13", "epic": "EPIC-06", "feature": "F-13", "priority": "P0", "points": "3", "sprint": "S3",
     "labels": "user-story;frontend",
     "ac": "Events: PipelineStarted, AgentTaskCompleted, ApprovalGranted, Rejected, Completed. Agent events show model_id. Append-only. Included in export."},
    {"type": "User Story", "id": "US-24", "title": "Pipeline survives worker restart",
     "desc": "As a platform engineer, I want workflow resume after restart.",
     "parent": "FEAT-03", "epic": "EPIC-06", "feature": "F-03", "priority": "P0", "points": "3", "sprint": "S2",
     "labels": "user-story;workflow",
     "ac": "Worker restart resumes within 2 min. Approve signal works after API restart. No duplicate asset versions."},
    {"type": "User Story", "id": "US-25", "title": "API token authentication",
     "desc": "As a platform engineer, I want Bearer token on mutating endpoints.",
     "parent": "FEAT-INFRA", "epic": "EPIC-06", "feature": "F-INFRA", "priority": "P0", "points": "2", "sprint": "S2",
     "labels": "user-story;security",
     "ac": "No token on POST returns 401. Valid Bearer succeeds. Web client sends token from env."},
    {"type": "User Story", "id": "US-26", "title": "App navigation shell",
     "desc": "As a creator, I want nav between Dashboard, Review, Assets, Audit, Export.",
     "parent": "FEAT-16", "epic": "EPIC-06", "feature": "F-16", "priority": "P0", "points": "2", "sprint": "S2",
     "labels": "user-story;frontend",
     "ac": "Nav bar on all screens. Empty states when pipeline not started. CTA reflects current stage. Usable at >=768px."},
    {"type": "User Story", "id": "US-27", "title": "MVP demo acceptance validation",
     "desc": "As a product owner, I want demo script executable end-to-end.",
     "parent": "FEAT-15", "epic": "EPIC-05", "feature": "F-15", "priority": "P0", "points": "2", "sprint": "S5",
     "labels": "user-story;qa",
     "ac": "All 10 demo steps pass. SC-01 to SC-08 verified. Limitations documented. Stakeholder sign-off."},
]

# Tasks keyed by story
TASKS = {
    "US-01": [
        ("T-01-01", "Create projects table migration"),
        ("T-01-02", "Implement seed script for default project"),
        ("T-01-03", "Add GET /projects endpoint"),
        ("T-01-04", "Unit test project repository"),
    ],
    "US-02": [
        ("T-02-01", "Write docker-compose.yml for all 9 services"),
        ("T-02-02", "Configure PostgreSQL volume and init scripts"),
        ("T-02-03", "Configure MinIO bucket aimpos-hot-assets on startup"),
        ("T-02-04", "Pin Ollama model llama3.1:13b in compose init"),
        ("T-02-05", "Document Olares deployment in README"),
        ("T-02-06", "Verify zero egress during compose startup"),
    ],
    "US-03": [
        ("T-03-01", "Implement /health with dependency probes"),
        ("T-03-02", "Add structured logging middleware"),
        ("T-03-03", "Add request ID propagation"),
    ],
    "US-04": [
        ("T-04-01", "Define SQLAlchemy models for core tables"),
        ("T-04-02", "Create initial Alembic migration"),
        ("T-04-03", "Add repository layer interfaces"),
    ],
    "US-05": [
        ("T-05-01", "Implement MinIO client wrapper"),
        ("T-05-02", "Implement content-hash key generator"),
        ("T-05-03", "Implement AssetVersion create on upload"),
        ("T-05-04", "Integration test upload round-trip"),
    ],
    "US-06": [
        ("T-06-01", "Create Ollama connectivity test script"),
        ("T-06-02", "Pin and test ComfyUI SDXL workflow JSON"),
        ("T-06-03", "Document GPU sequencing rule in worker README"),
    ],
    "US-07": [
        ("T-07-01", "Deploy Temporal server with PostgreSQL persistence"),
        ("T-07-02", "Implement SparkPipelineWorkflow skeleton"),
        ("T-07-03", "Implement POST /pipeline/start API"),
        ("T-07-04", "Implement GET /pipeline/status API"),
        ("T-07-05", "Register Temporal worker pod"),
        ("T-07-06", "Write audit event on pipeline start"),
    ],
    "US-08": [
        ("T-08-01", "Implement approval API endpoints"),
        ("T-08-02", "Wire Temporal approve/reject signals"),
        ("T-08-03", "Create immutable approvals table writes"),
        ("T-08-04", "Handle reject without workflow advance"),
        ("T-08-05", "Integration test approve advances stage"),
    ],
    "US-09": [
        ("T-09-01", "Implement regenerate endpoint"),
        ("T-09-02", "Pass rejection note to activity input"),
        ("T-09-03", "Enforce max 3 regenerations per stage"),
        ("T-09-04", "Increment version on regenerate"),
    ],
    "US-10": [
        ("T-10-01", "Implement dashboard API aggregation endpoint"),
        ("T-10-02", "Build Dashboard screen (React)"),
        ("T-10-03", "Add 5-stage progress stepper component"),
        ("T-10-04", "Implement status polling hook"),
    ],
    "US-11": [
        ("T-11-01", "Implement POST /ideas endpoint"),
        ("T-11-02", "Build idea capture form on Dashboard"),
        ("T-11-03", "Validate input length and required fields"),
        ("T-11-04", "Store idea as asset_version stage=IDEA"),
    ],
    "US-12": [
        ("T-12-01", "Implement LangGraph Story Architect graph"),
        ("T-12-02", "Implement run_story_agent Temporal activity"),
        ("T-12-03", "Create story prompt template with idea injection"),
        ("T-12-04", "Store story output as asset version"),
        ("T-12-05", "Log agent invocation to audit_events"),
        ("T-12-06", "Integration test story generation (mock Ollama)"),
    ],
    "US-13": [
        ("T-13-01", "Build Review screen — story mode"),
        ("T-13-02", "Implement PUT /assets/{id} text update"),
        ("T-13-03", "Wire Approve/Reject buttons to pipeline API"),
        ("T-13-04", "Display rejection note input on reject"),
    ],
    "US-14": [
        ("T-14-01", "Implement LangGraph Screenwriter graph"),
        ("T-14-02", "Implement run_script_agent Temporal activity"),
        ("T-14-03", "Add Fountain format validation"),
        ("T-14-04", "Record lineage edge story to script"),
        ("T-14-05", "Store script asset version"),
    ],
    "US-15": [
        ("T-15-01", "Build Review screen — script mode with Fountain preview"),
        ("T-15-02", "Add basic Fountain-to-HTML formatter"),
        ("T-15-03", "Wire approve/reject for script stage"),
        ("T-15-04", "Mark approved script version in DB"),
    ],
    "US-16": [
        ("T-16-01", "Implement Cinematography agent (planning via Ollama)"),
        ("T-16-02", "Implement ComfyUI tool — SDXL/Flux workflow"),
        ("T-16-03", "Implement run_storyboard_agent Temporal activity"),
        ("T-16-04", "GPU sequencing: unload Ollama before ComfyUI"),
        ("T-16-05", "Store multiple frame assets per run"),
        ("T-16-06", "Record lineage edges script to frames"),
        ("T-16-07", "ComfyUI error handling and retry"),
    ],
    "US-17": [
        ("T-17-01", "Build Review screen — storyboard gallery mode"),
        ("T-17-02", "Implement image preview lightbox"),
        ("T-17-03", "Wire approve-all / reject for storyboard stage"),
        ("T-17-04", "Display AI badge and model on frames"),
    ],
    "US-18": [
        ("T-18-01", "Implement ComfyUI image-to-video workflow"),
        ("T-18-02", "Implement run_video_agent Temporal activity"),
        ("T-18-03", "Implement slideshow fallback generator (FFmpeg)"),
        ("T-18-04", "Store video asset with duration/resolution metadata"),
        ("T-18-05", "Record lineage frames to video"),
        ("T-18-06", "End-to-end GPU test on Olares hardware"),
    ],
    "US-19": [
        ("T-19-01", "Build Review screen — video player mode"),
        ("T-19-02", "Wire approve/reject for video stage"),
        ("T-19-03", "Set pipeline status COMPLETED on final approval"),
        ("T-19-04", "Write PipelineCompleted audit event"),
    ],
    "US-20": [
        ("T-20-01", "Implement GET /lineage/{pipeline_run_id} API"),
        ("T-20-02", "Build Lineage summary component on Export screen"),
        ("T-20-03", "Render chain visualization (simple list/tree)"),
    ],
    "US-21": [
        ("T-21-01", "Implement finalize_export Temporal activity"),
        ("T-21-02", "Implement GET /export/{pipeline_run_id} ZIP builder"),
        ("T-21-03", "Generate manifest.json with hashes and metadata"),
        ("T-21-04", "Build Export screen with download button"),
    ],
    "US-22": [
        ("T-22-01", "Implement GET /assets?project_id=&stage= API"),
        ("T-22-02", "Build Assets screen with stage tabs"),
        ("T-22-03", "Implement version list and preview components"),
        ("T-22-04", "Add download link per version"),
    ],
    "US-23": [
        ("T-23-01", "Implement GET /audit?pipeline_run_id= API"),
        ("T-23-02", "Build Audit screen table"),
        ("T-23-03", "Standardize audit event schema across worker"),
        ("T-23-04", "Include audit summary in export manifest"),
    ],
    "US-24": [
        ("T-24-01", "Configure Temporal worker graceful shutdown"),
        ("T-24-02", "Test worker restart during review wait"),
        ("T-24-03", "Test worker restart during activity execution"),
        ("T-24-04", "Document recovery behavior"),
    ],
    "US-25": [
        ("T-25-01", "Implement Bearer token middleware"),
        ("T-25-02", "Configure token via environment variable"),
        ("T-25-03", "Wire token into React API client"),
    ],
    "US-26": [
        ("T-26-01", "Build app shell with React Router"),
        ("T-26-02", "Implement nav bar and route guards"),
        ("T-26-03", "Add empty states per screen"),
    ],
    "US-27": [
        ("T-27-01", "Execute demo acceptance script"),
        ("T-27-02", "Document success metrics results"),
        ("T-27-03", "Write MVP release notes"),
        ("T-27-04", "Stakeholder demo and sign-off"),
    ],
}

# Build full item list with tasks
story_lookup = {i["id"]: i for i in ITEMS if i["type"] == "User Story"}
all_items = list(ITEMS)
for story_id, tasks in TASKS.items():
    story = story_lookup[story_id]
    for tid, title in tasks:
        all_items.append({
            "type": "Task",
            "id": tid,
            "title": title,
            "desc": f"Implementation task for {story_id}: {title}",
            "parent": story_id,
            "epic": story["epic"],
            "feature": story["feature"],
            "priority": story["priority"],
            "points": "",
            "sprint": story["sprint"],
            "labels": "task",
            "ac": "",
        })


def write_csv(path, fieldnames, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for item in rows:
            w.writerow(item)


# Universal CSV
universal_fields = [
    "Work Item Type", "ID", "Title", "Description", "Parent ID", "Epic ID",
    "Feature ID", "Priority", "Story Points", "Sprint", "Labels", "Acceptance Criteria",
]
universal_rows = [{
    "Work Item Type": i["type"],
    "ID": i["id"],
    "Title": i["title"],
    "Description": i["desc"],
    "Parent ID": i["parent"],
    "Epic ID": i["epic"],
    "Feature ID": i["feature"],
    "Priority": i["priority"],
    "Story Points": i["points"],
    "Sprint": i["sprint"],
    "Labels": i["labels"],
    "Acceptance Criteria": i["ac"],
} for i in all_items]
write_csv(OUT / "aimpos-spark-backlog.csv", universal_fields, universal_rows)

# Jira CSV
epic_titles = {i["id"]: i["title"] for i in ITEMS if i["type"] == "Epic"}
jira_type_map = {"Epic": "Epic", "Feature": "Story", "User Story": "Story", "Task": "Sub-task"}
jira_fields = [
    "Issue Type", "Summary", "Description", "Issue Key", "Parent ID",
    "Epic Name", "Epic Link", "Feature ID", "Priority", "Story Points",
    "Sprint", "Labels", "Acceptance Criteria",
]
jira_rows = []
for i in all_items:
    epic_name = epic_titles.get(i["epic"], i["epic"])
    labels = i["labels"]
    if i["type"] == "Feature":
        labels = f"{labels};type:feature"
    jira_rows.append({
        "Issue Type": jira_type_map[i["type"]],
        "Summary": f"[{i['id']}] {i['title']}",
        "Description": i["desc"],
        "Issue Key": i["id"],
        "Parent ID": i["parent"],
        "Epic Name": epic_name if i["type"] in ("User Story", "Feature") else "",
        "Epic Link": i["epic"] if i["type"] in ("User Story", "Feature") else "",
        "Feature ID": i["feature"],
        "Priority": i["priority"],
        "Story Points": i["points"],
        "Sprint": i["sprint"],
        "Labels": labels,
        "Acceptance Criteria": i["ac"],
    })
write_csv(OUT / "aimpos-spark-backlog-jira.csv", jira_fields, jira_rows)

# Azure DevOps CSV
ado_type_map = {"Epic": "Epic", "Feature": "Feature", "User Story": "User Story", "Task": "Task"}
sprint_ado = {"S1": "AIMPOS-Spark\\Sprint 1", "S2": "AIMPOS-Spark\\Sprint 2",
              "S3": "AIMPOS-Spark\\Sprint 3", "S4": "AIMPOS-Spark\\Sprint 4",
              "S5": "AIMPOS-Spark\\Sprint 5", "S1-S5": "AIMPOS-Spark"}
ado_fields = [
    "Work Item Type", "Title", "Description", "Work Item ID", "Parent Work Item ID",
    "Area Path", "Iteration Path", "Feature ID", "Priority", "Story Points",
    "Tags", "Acceptance Criteria",
]
ado_rows = []
for i in all_items:
    sprint = i["sprint"]
    iteration = sprint_ado.get(sprint.split("-")[0] if sprint.startswith("S1-S") else sprint, "AIMPOS-Spark")
    if sprint == "S1-S5":
        iteration = "AIMPOS-Spark"
    ado_rows.append({
        "Work Item Type": ado_type_map[i["type"]],
        "Title": f"[{i['id']}] {i['title']}",
        "Description": i["desc"],
        "Work Item ID": i["id"],
        "Parent Work Item ID": i["parent"],
        "Area Path": "AIMPOS-Spark",
        "Iteration Path": iteration,
        "Feature ID": i["feature"],
        "Priority": i["priority"] or "2",
        "Story Points": i["points"],
        "Tags": i["labels"].replace(";", "; "),
        "Acceptance Criteria": i["ac"],
    })
write_csv(OUT / "aimpos-spark-backlog-ado.csv", ado_fields, ado_rows)

print(f"Generated {len(all_items)} work items:")
print(f"  Epics: {sum(1 for i in all_items if i['type']=='Epic')}")
print(f"  Features: {sum(1 for i in all_items if i['type']=='Feature')}")
print(f"  User Stories: {sum(1 for i in all_items if i['type']=='User Story')}")
print(f"  Tasks: {sum(1 for i in all_items if i['type']=='Task')}")
print(f"  Story Points: {sum(int(i['points']) for i in all_items if i['points'])}")
